name: text
on:
  workflow_dispatch:
  schedule:
    - cron: '15,30 5,23 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BINTA_SLACK_INCOMING_WEBHOOK_URL: ${{ secrets.BINTA_SLACK_INCOMING_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.2'
          elixir-version: '1.14.2'
      - run: mix deps.get
      - run: mix test